### ISSUE TITLE
为何我得到的回调地址为空呢

### ISSUE THREAD

**Issue by hetykai** [WeCase/rpweibo#5]
前面的代码已经登陆成功了，手机微博客户端可以收到已经在其他地方登陆成功的消息，微博上已经设置回调地址为默认地址了，代码中写的也是一样的默认回调地址，但是执行到这一步的回调地址却是None导致无法得到code，然后就无法得到token了，不知道为啥这里会是None？
求帮助，不要删库。。。真诚的求大神指导

![2017-03-22_185146](https://cloud.githubusercontent.com/assets/3378432/24194539/6be5b4b2-0f31-11e7-98c7-4a12da3003d3.jpg)

**Comment by biergaizi** [comment]
在新浪后台把 CALLBACK_URL 设置为 'https://api.weibo.com/oauth2/default.html'，并在使用 API 时传递相同参数。

**Comment by Garfield550** [comment]
另外这个库不会删的，如果你有兴趣，可以参入进来一起改进这个库 👍

**Comment by hetykai** [comment]
昨天我试过了把新浪后台和application的回调地址都同时设置为https://api.weibo.com/oauth2/default.html，但是返回的始终不是302重定向，是200，也就得不到code，不过我的需求是只需要获取token就行了，我本身对python并不是太熟悉，所以最终用手动的方式来获取code了。谢谢两位的解答，这个我就先关了。☺
